### ISSUE TITLE
[Questions] CI environment & `development` versus `production` builds

### ISSUE THREAD

**Issue by pruett** [segmentio/typewriter#102]
Hey. I've really been enjoying the new release of Typewriter v7. I did have 2 questions, however, that I was hoping to get some further clarification on.

1. How does Typewriter work in a CI environment? I'm using a [Token Script](https://segment.com/docs/protocols/typewriter/#token-script) to supply the token during client generation. However, I have nothing set up in our CI environment and the client generation surprisingly _works_. Does the library use an internal token in CI-based environments?

2. I wasn't able to find any difference in running these two commands: `npx typewriter development` and `npx typewriter production`. Out of curiosity, should these commands produce different outputs given a Browser-based/TypeScript setup?

**Comment by colinking** [comment]
Hey @pruett! Glad to hear that :)

1. `npx typewriter development` and `npx typewriter production` just build generated clients from your `plan.json`, so it doesn't need to query the Segment API. However, `npx typewriter` will try to update your `plan.json` by querying the Segment API. If that fails, it just logs a warning and continues. I'd recommend using `development/production` in CI though: https://segment.com/docs/protocols/typewriter/#connecting-to-ci

2. That's odd! The development build will include run-time schema validation logic using AJV. This requires us to embed your entire Tracking Plan inside the generated client, so this is relatively heavy (especially in browser environments). The production build will skip all of that. Do you see a [`import AJV from 'ajv'` line at the top](https://github.com/segmentio/typewriter/blob/b3c2c327b15ba08b4d5321345b4212d2ecdb3d3b/src/generators/javascript/templates/index.hbs#L5-L15)?

**Comment by colinking** [comment]
As a side-note, the iOS client doesn't yet support run-time validation, so the development and production clients are identical there: https://github.com/segmentio/typewriter/issues/96

**Comment by pruett** [comment]
> However, `npx typewriter` will try to update your `plan.json` by querying the Segment API

Ahh...this makes sense. For some reason I thought `npx typewriter` was an alias for `npx typewriter development`. Not sure where I got that impression. But this makes perfect sense. Thanks!

> The production build will skip all of that. Do you see a `import AJV from 'ajv'` line at the top?

I'll double-check this and report back.

Many thanks!

**Comment by colinking** [comment]
Yeah, you're right on -- it calls `npx typewriter development` after pulling down the latest changes:

```
$ typewriter --help
...
  Commands:
    update            Syncs plan.json with Segment, then generates a           (default)
                      development client.
    dev               Generates a development client from plan.json
```

**Comment by pruett** [comment]
Apologies, I am seeing a difference in production versus development builds on the client. Thanks for the explanation and source code reference!
