### ISSUE TITLE
iOS does not serialize null values

### ISSUE THREAD

**Issue by colinking** [segmentio/typewriter#114]
This is due to how `analytics-ios` doesn't support serializing null values: https://github.com/segmentio/analytics-ios/pull/707

This was recently fixed here: https://github.com/segmentio/analytics-ios/issues/852

But hasn't been released yet. When a new version of `analytics-ios` is released, we can update the test suite to validate that we start serializing null values: https://github.com/segmentio/typewriter/blob/769e650476545c290e3c8b999e0303aa9e321d26/tests/e2e/suite.test.ts#L159

**Comment by bsneed** [comment]
This has been released now.
