### ISSUE TITLE
Suggestion: Typescript only mode

### ISSUE THREAD

**Issue by mattvagni** [segmentio/typewriter#120]
At [@echo-health](https://github.com/echo-health) use Typescript in all of our projects and were wondering whether there would be any interest in adding a 'mode' to Typewriter so that it only outputs types that enforce the tracking schema instead of javascript code. **We would be happy to take this on as a contribution**

This would be preferable for us for the following reasons:

- It would not impact our bundle size in production at all
- It would circumvent any issues around browser support + proxies (like: https://github.com/segmentio/typewriter/issues/119)

I'm intentionally not going to propose any naming or CLI flags here to first be able to talk about the idea in principle.

Should you not want this to be in-scope of this project, would you be ok with a separate community contributed package (e.g. Something like `ts-typewriter` or the like)?

**Comment by colinking** [comment]
Hey @mattvagni! Love the idea :) If you want to generate just TS declarations for `analytics.js`'s `track` call, then you'd probably want to do something like this:

```ts
declare module 'analytics.js' {
	track: (event: 'Order Completed', properties: { id: string }) => void
		 | (event: 'Order Delivered', properties: { id: string }) => void
		 | (event: 'Order Viewed') => void
		 | // ...
}
```

But I'm not sure how well TS works with discriminated unions with 10s/100s of values. IIRC, I ran into similar issues before with some typed JSONRPC work. You might want to give that a shot manually and see if it'll work for y'all :)

If that all goes well, I'd recommend maintaining this as an upstream fork of `typewriter`, since there'd be a few last-mile-delivery items to ship before merging to `master` (add an `e2e/` test, docs, updating `typewriter init`, etc.).

**Comment by mattvagni** [comment]
@colinking Wonderful! We'll look into this. 

One question I do have before getting started: given this actually would just be additional type annotations for `window.analytics.track`, we could actually make this change without having to introduce any new config options in `typewriter.yml`.

The only downside I can see of this is that if a client of yours is migrating a codebase to typewriter (like us) they will have to do something like this `(window.analytics as SegmentAnalytics.AnalyticsJS).track('bloop')` for events they are tracking that are not in their tracking plan yet.

Do you think this is an ok approach or would your rather enable/disable this new behaviour behind a flag?

**Comment by colinking** [comment]
I think a flag of some kind makes the most sense!

I'd expect folks would either want to instrument typewriter using generated functions, or they'd want to use `analytics.*` methods directly, so it's better to generate code that only offers a single way to instrument analytics. Making it opt-in would also make any changes backwards compatible, as you brought up :)

**Comment by correttojs** [comment]
maybe a bit late, here is my implementation:

```
import type typewriter from '../../@types/typewriter';

type FilterFunc<T> = T extends Function ? T : never;
type SegmentClientType = typeof typewriter;
type SegmentClientKeysType = keyof SegmentClientType;
type SegmentClientFuncType<T extends SegmentClientKeysType> = FilterFunc<SegmentClientType[T]>;

export const trackEvent = <T extends SegmentClientKeysType>(method: T, args: Parameters<SegmentClientFuncType<T>>[0]) => {
    analytics.track(method, args)
}
```

and you can always import typewriter in dev mode only, so you also get runtime checks

**Comment by mattvagni** [comment]
No longer using Segment unfortunately and have not had a chance to update this in a while... closing!
