### ISSUE TITLE
Typewriter does not respect TYPEWRITER_TOKEN env var

### ISSUE THREAD

**Issue by madisonbullard** [segmentio/typewriter#134]
bug report 🐞

OS: Mac 10.15.3
Typewriter: 7.1.0
javascript

From the "API Token Configuration" docs:
>Typewriter looks for an API token in three ways, in the following order:
>1. Looks for an environment variable called TYPEWRITER_TOKEN.
>2. Executes a token script from the typewriter.yml. See Token Script for more information.
>3. Reads the contents of a ~/.typewriter file.
https://segment.com/docs/protocols/apis-and-extensions/typewriter/#api-token-configuration

When I run `npx typewriter` while passing `TYPEWRITER_TOKEN` to the env, the token is not recognized by Typewriter. I have added logging on a local Typewriter build that indicates `process.env.TYPEWRITER_TOKEN` is properly populated, and Typewriter has access.

Looking through the code, it doesn't look like Typewriter is ever looking for the env var. The `listTokens` function only checks `~/.typewriter` and the token script.

Perhaps this is something that made its way into the docs without ever being implemented?

**Comment by colinking** [comment]
Good catch, @madisonbullard. We originally supported environment variables, but decided to cut it to conceptually simplify how CLI auth works. You can get this same behavior via a token script (`echo $TYPEWRITER_TOKEN`). LMK if that works for you!

Here's an example:

```yml
scripts:
  token: echo $TYPEWRITER_TOKEN
```

```sh
❯ TYPEWRITER_TOKEN=foobar yarn typewriter tokens

  scripts.token:      foobar...      (invalid token)
  ~/.typewriter:      (snip)...  

  Tip: For more information on configuring an API token, see the online docs.

✨  Done in 1.29s.
```

And I'll look into updating the docs to reflect this 👍

**Comment by colinking** [comment]
Docs update is live: https://segment.com/docs/protocols/apis-and-extensions/typewriter/#api-token-configuration
