### ISSUE TITLE
Android SDK: required property not enforced if type can be null

### ISSUE THREAD

**Issue by vn01971** [segmentio/typewriter#147]
I'm using the analytics-android java sdk and Typewriter v7.2.1.
### json schema
```
"properties": {
  "someProperty": {
    "type": "string" 
  }
},
"required": [
  "someProperty"
]
```
### generated builder output
```java
public TestEvent build() {
  if(properties.get("someProperty") == null){
      throw new IllegalArgumentException("TestEvent missing required property: someProperty");
  }
  return new TestEvent(properties);
}
```

### json schema
```
"properties": {
  "someProperty": {
    "type": ["string", "null"] 
  }
},
"required": [
  "someProperty"
]
```
### generated builder output
```java
public TestEvent build() {
  return new TestEvent(properties);
}
```

Is this the expected behavior?

**Comment by alanjcharles** [comment]
Hi @vn01971  scrubbing the issues here since a lot of them are old and stale. If you still have questions about this behavior please feel free to reach out to us at friends@segment.com. Thanks!

**Comment by vn01971** [comment]
Hi @alanjcharles,

I will reach out to friends@segment.com, but posting here as well for visibility:

If the property type can be `null` but it's also required, I would expect it to generate something like the following:
```java
  if(!properties.containsKey("someProperty")){
      throw new IllegalArgumentException("TestEvent missing required property: someProperty");
  }
  return new TestEvent(properties);
```

Could you explain why the current behavior is to not check that `properties` contains a required property if that property can be `null`?
