### ISSUE TITLE
Unable to Integrate Typewriter with CircleCI

### ISSUE THREAD

**Issue by CrystalToh** [segmentio/typewriter#148]
## Issue

My team and I have been trying to integrate Typewriter to our application by following the provided [Typewriter documentation](https://segment.com/docs/protocols/apis-and-extensions/typewriter/).
Attempts at following the [Best Practices](https://segment.com/docs/protocols/apis-and-extensions/typewriter/#best-practices) and [Connecting to CI](https://segment.com/docs/protocols/apis-and-extensions/typewriter/#connecting-to-ci) sections have resulted in an error when CircleCI attempts to run the `npx typewriter production` command.
We would appreciate any assistance in helping to resolve this problem, or guidance for any additional setup that might be necessary to get this working as expected.

## Steps to Reproduce

1. Edit the application's CircleCI config.yml file to run the `npx typewriter production` command before the `yarn run deploy` line, as shown in the documentation [here](https://segment.com/docs/protocols/apis-and-extensions/typewriter/#connecting-to-ci).
2. Push the changes and allow CircleCI to run through the commands.
3. Observe the output.

## Versions

Typewriter: 7.2.1

## Screenshots

<img width="1156" alt="Screenshot 2020-10-22 at 16 15 21" src="https://user-images.githubusercontent.com/6405472/96845337-280acd80-1483-11eb-911f-b8685d0f45cf.png">

## Expected

The `npx typewriter production` command runs without any errors, and the Typewriter client (index.js) is generated at the specified directory.

## Actual

CircleCI throws the following error upon running the `npx typewriter production` command:
```
Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
```

**Comment by njausteve** [comment]
@colinking @gurdasnijor @mshwery @bryantbiggs @vadimdemedes @bsneed any comments on this?
