### ISSUE TITLE
Unable to compile generated Typescript for analytics-node sdk

### ISSUE THREAD

**Issue by hitherejoe** [segmentio/typewriter#157]
Hey all - i'm really enjoying using typewriter, thanks for the work here! We've adopted it in our mobile team and are looking at expanding this into our web codebases.

I've generated my typewriter code (`sdk: analytics-node language: typescript`) using `npx typewriter`, which succesfully generates the `index.ts` and `segment.ts` files. However, there are a bunch of compilation errors within the `index.ts` file which are preventing the project from being built. E.g:

<img width="782" alt="Screenshot 2021-01-05 at 15 11 03" src="https://user-images.githubusercontent.com/3879281/103662773-40f62b80-4f68-11eb-8933-42d38c93e3ea.png">

Is there something i'm missing here or could this be an issue with types not being generated correctly? 🤔 

Apologies if I'm missing something obvious, but I thought others might run into (or have already run into) the same issue so felt it worth reaching out. Thanks for your time!

**Comment by hitherejoe** [comment]
So within the generated `segment.ts` file, this error is shown:

<img width="1430" alt="Screenshot 2021-01-07 at 13 10 09" src="https://user-images.githubusercontent.com/3879281/103896647-34014580-50ea-11eb-81ed-47058b64ed6b.png">

Adding the declaration file clears the error, but causes the following error in the generated `index.ts`

<img width="1232" alt="Screenshot 2021-01-07 at 13 44 01" src="https://user-images.githubusercontent.com/3879281/103899524-6e6ce180-50ee-11eb-85d4-8d9e5c4ae1c0.png">

I removed the declaration file and tried running `npm i --save-dev @types/analytics-node`. This also clears the error, but then this causes a lot of errors to occur in the generated `index.ts` file. 

<img width="944" alt="Screenshot 2021-01-07 at 13 46 03" src="https://user-images.githubusercontent.com/3879281/103899722-b429aa00-50ee-11eb-997e-3cde558d3537.png">

It looks like the track function is what is causing the error here, jumping into the source for that function opens up the track function within the types/analytics-node package that was just installed. However, that package is needed to allow the `segment.ts` file to compile.

Am i missing something here? Is there a way to configure the types so that both the `index.ts` and `segment.ts` files compile? cc/ @colinking

**Comment by hitherejoe** [comment]
OK so after some digging, this looks like there is an issue with the types definition 🤔 

Looking at DefinitelyTyped, I can see [a change was made ](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/849d8328315c8d6986861a08aeb3bb3b2be7550c) to enforce one of either the userId or anonymousId

    type Identity =
        | { userId: string | number }
        | { userId?: string | number; anonymousId: string | number };

I'm not sure if this is specifically because how our tracking plan is configured, or if it's an issue with the way the types are defined. Either way, this is what is causing the causing the typing error as shown above for the `msg` variable. I'm not an expert with Typescript but looking at the generated `segment.ts` file we can see that both the `userId` and `anonymousId` are marked as optional:

    export interface TrackMessage<PropertiesType>
	extends Options,
		Record<string, any> {
	/** The ID for this user in your database. */
	userId?: string | number
	/** An ID to associated with the user when you don’t know who they are. */
	anonymousId?: string | number
	...
    }

Looking at the defined type for Identity, I don't think this satisfies what is generated in the `segment.ts`, as both `userId` and `anonymousId` can be optionals

**Comment by harmvandendorpel** [comment]
I fixed this for now by adding an `override.d.ts` file containing:
```
// this file fixes an issue until typewriter / analytics.node is fixed
// https://github.com/segmentio/typewriter/issues/157

declare namespace AnalyticsNode {
  type Identity =
    | { userId?: string | number; anonymousId?: string | number };
}

```

**Comment by tvelich** [comment]
encountering same issue. opened pr to align with the `analytics-node` change and kick off a discussion

**Comment by alanjcharles** [comment]
Hi everyone! Thanks for submitting that pr @tvelich. I think it makes sense and shouldn't impact anything else. I'm going to go ahead and merge unless @hitherejoe or anyone else has any comment. Doing a general clean up of the repo and will push a release later this week. 

For reference: https://github.com/segmentio/typewriter/pull/165

**Comment by tvelich** [comment]
> Hi everyone! Thanks for submitting that pr @tvelich. I think it makes sense and shouldn't impact anything else. I'm going to go ahead and merge unless @hitherejoe or anyone else has any comment. Doing a general clean up of the repo and will push a release later this week.
> 
> For reference: #165

Can you hold off on merging that?

Further going through some of the segment docs I see examples with both `userId` and `anonymousId` present so I can update to reflect that:
1. Either`userId` or `anonymousId` _must_ be provided
2. If providing either, the other becomes optional

Similar to: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/849d8328315c8d6986861a08aeb3bb3b2be7550c#diff-658e63acf6afe3bb6292916b8556fbaf7a7fc85fd16d4c5d666732a340b0d60aR11-R15
