### ISSUE TITLE
Error running typewriter init 

### ISSUE THREAD

**Issue by vianch** [segmentio/typewriter#161]
## Bug report 🐞

* Issue and steps to reproduce.
* Versions. (Typewriter, OS, language, etc.)
IOS: macOS big sur
node: 14.15.5
typewriter 7.4.1 

* Screenshots.
![Screen Shot 2021-03-09 at 3 33 53 PM](https://user-images.githubusercontent.com/1800887/110534342-f40c0e00-80ec-11eb-832f-24f9af7b7967.png)

* Expected.
new typewriter.yml and ./analytics 

* Actual.
error: TypeError: setRawMode is not a function

* Minimal reproducible example.
run `npx typewriter init` or `typewriter init`

**Comment by bsneed** [comment]
@vianch could you contact Segment support and create a ticket through there?  Having your API token would be helpful in debugging.

**Comment by bsneed** [comment]
Ah gotcha.  Yes, we have no tested it with that yet unfortunately.

**Comment by dwjohnston** [comment]
Duplicate of https://github.com/segmentio/typewriter/issues/139
