### ISSUE TITLE
"npx typewriter init" does not show the wizard

### ISSUE THREAD

**Issue by HughIngram** [segmentio/typewriter#162]
- typewriter version: 7.4.1
- node version: 10.19.0
- npm version: 6.14.4
- npx version: 6.14.4
- OS: Ubuntu 20.04

When I run `npx typewriter init`, I expect that I should see an interactive wizard in the terminal. Instead, it only shows:

- a progress indicator
- then `npx: installed 157 in 9.95s`
- then `  Typewriter is a tool for generating strongly-typed Segment analytics libraries `
- then it shows whitespace, and does not exit.

![Screenshot from 2021-03-19 16-47-01](https://user-images.githubusercontent.com/6364856/111806933-c5ebb280-88d2-11eb-96e0-969c18196371.png)

**Comment by alanjcharles** [comment]
Hi  @HughIngram please try updating your NPM version to `7.6.1` and let me know if the problem persists.
