### ISSUE TITLE
Version bump to 4.7.2 to resolve vulnerabilities

### ISSUE THREAD

**Issue by ajermaky** [segmentio/typewriter#220]
Hi! I wanted to propose that a 4.7.2 release be done to address some of the security issues that are present in 4.7.1. I believe main branch has already resolved most of them, but its just not part of the official release. Not sure what the release lifecycle is like, but if there are any roadblocks, like updating packages, etc. happy to help here!

**Comment by Nederby** [comment]
This seems critical. Any blocker that you need help resolving, so we can get a patch out for this?
 
<img width="1311" alt="Screenshot 2022-06-23 at 08 46 20" src="https://user-images.githubusercontent.com/6588469/175233164-dd92644e-18d6-4e4f-b9b8-d460ea832b8b.png">

https://github.com/advisories/GHSA-f2jv-r9rf-7988

**Comment by oscb** [comment]
This is finally fixed in v8. Sorry for the wait

**Comment by Sparkenstein** [comment]
@oscb  As per your comment, critical vuln was fixed in 8.x.x. But what about users who are using v7 and not ready to migrate yet? 
There should be a release for v7.4.2 that fixes this.

**Comment by oscb** [comment]
@Sparkenstein I know this is not a great answer but I'm going to be honest. v7 doesn't build and it's poorly documented internally. I bet it's just a matter of redoing the updates of the packages between v7.4.1 and the latest version but at this point we just don't have the resources to go and fix it. 

I would be happy to review any PR for v7 and trigger a release
