### ISSUE TITLE
Release version 7.4.2 to support React 17

### ISSUE THREAD

**Issue by ashleyqw** [segmentio/typewriter#241]
Hello, I wanted to ask when (and request that) 7.4.2 will be released. Not sure how release schedule works here, but it looks like @seanhealy has already fixed the issue in https://github.com/segmentio/typewriter/pull/232
Thanks!

**Comment by BrunoApparecido** [comment]
Do you have any news about the release?
We need to use React 17 but we are getting error in this library

**Comment by ryaninvents** [comment]
I tried pinning to a github/hash version to get around this problem, but for some reason the binary is not being built/loaded into `node_modules/.bin` so I can't use it.

<details>
<summary>Attempted solution (did not work)</summary>

```
"typewriter": "segmentio/typewriter#ef31caa3dc7c9fe960a1592f99d9a55f5feae4e1"
```

</details>


See also #209

**Comment by ryaninvents** [comment]
In case this unblocks someone: try `npx typewriter@next`. This worked for me.

**Comment by jordanskole** [comment]
Any reason this is stalled? I am currently blocked on using typewriter (a big reason we bought protocols) by this as well

**Comment by oscb** [comment]
[v8+](https://github.com/segmentio/typewriter/releases/tag/v8.0.4) don't have a dependency on React anymore!
