### ISSUE TITLE
Is `analytics-next` officially supported?

### ISSUE THREAD

**Issue by danielmhanover** [segmentio/typewriter#259]
I noticed this lib has a dependency on `window.analytics` and `@types/segment-analytics` and so I'm wondering if this library has been tested against the newer `analytics-next` lib for Segment?

**Comment by ameliejyc** [comment]
Hi, I also have this same question. We're currently using the `analytics-next` library but to integrate with Typewriter, it looks like we need to add the [Segment snippet](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/#step-2-add-the-segment-snippet) additionally. Is that to be expected or should we be able to get it working without the snippet?

**Comment by tplessis** [comment]
Hello, same problem here, types are incompatible for `window.analytics` : `analytics-next` use `AnalyticsSnippet` and typewriter use `AnalyticsJS`.

**Comment by richessler** [comment]
Hello, also curious here - is this currently supported?

**Comment by jriall** [comment]
Hi, we are also looking to implement Typewriter but cannot see an obvious way to do it with our current implementation of `analytics-next`. It would be great if this could be added to the library.

**Comment by jriall** [comment]
After digging into this more I found that it seems possible to get typewriter to play nice with analytics-next. The blocker was that the default analytics used by typewriter is window.analytics which is not available when using analytics-next. Thankfully, you can set the analytics object to use yourself using setTypewriterOptions.

```
import { AnalyticsBrowser } from "@segment/analytics-next";

import { setTypewriterOptions } from "./your-generated-typewriter-client";

const analytics = new AnalyticsBrowser();
setTypewriterOptions({analytics});
```

From here all of your tracking events should work. The only caveat is that the analytics types are not the same (typewriter uses SegmentAnalytics.AnalyticsJS and analytics-next uses AnalyticsBrowser. So far I have just silenced the compiler/linter and it seems to work ok.

It would definitely be a lot better if there was first class support for analytics-next to avoid having to hack around the types in this way though - I can't have confidence that this won't break in future.

**Comment by tleunen** [comment]
Yeah it seems there are types conflict between the generated `Context` and the `AnalyticsContext`, especially for the `campaign` prop.

The `AnalyticsContext.campaign` has all the props being required, while the one being generated has all of them being optional.

**Comment by silesky** [comment]
⚠️ Typewriter has been upgraded to use `@segment/analytics-next` in v9.0.0 - https://github.com/segmentio/typewriter/releases/tag/v9.0.0

**Comment by tleunen** [comment]
@silesky What minimum version of analytics-next is compatible with typewriter v9?

We've used v1.38.0 previously, and when upgrading to the most recent v1.57.1, we found out that events were not sent to segment anymore (but only in production for some reasons) and it's been hard to debug this so we rollback to our previous version for now. (And btw, if you have an idea what could be the problem, I'd appreciate it a lot!)

The generated file uses an `AnalyticsSnippet` type from analytics-next that is not present in v1.38.0 so I was wondering if you knew which version introduces it?

**Comment by silesky** [comment]
@tleunen Maybe 1.43.1? There hasn't been any breaking changes -- maybe  a validation error (e.g. your anonymousId must be a string?)

You can do analytics.track(...).then(ctx =>  {
  const err = ctx.failedDelivery()
   if (err) { console.error(err) }
})

...to see why a particular event might have failed
