### ISSUE TITLE
Bug: validateAgainstSchema function is generated but never called

### ISSUE THREAD

**Issue by cjhensen** [segmentio/typewriter#271]
Bug: validateAgainstSchema function is generated but never called

Using the following settings in `typewriter.yml`
![image](https://user-images.githubusercontent.com/6188364/204854813-20ca1c2d-3c16-4def-be88-4b096fc5254e.png)

Hello Segment team!

We would like to make use of violation handling as detailed [here in your docs](https://segment.com/docs/protocols/apis-and-extensions/typewriter/#tracking-plan-violation-handling). When we generate the client with `npx typewriter`, we see the function `validateAgainstSchema` generated in the code, but it is not called anywhere. Seems like a bug, unless we're missing an option somewhere. Thanks!

**Comment by oscb** [comment]
Fixed in: https://github.com/segmentio/typewriter/releases/tag/v8.0.8

**Comment by cjhensen** [comment]
@oscb No problem! Thanks for confirming it's a bug!
