### ISSUE TITLE
Bug: New properties are not immediately pulled in when re-running npx typewriter

### ISSUE THREAD

**Issue by cjhensen** [segmentio/typewriter#273]
Hello Segment team!

Reproduction steps:
- Have an event in a tracking plan
- Generate the client with `npx typewriter`
- Look at the `plan.json` and verify that it contains your expected properties
- Add a new property to the tracking plan in the protocols UI
- Re-generate the client with `npx typewriter`
- Look at the `plan.json` - the new property does not exist

How we've gotten around this: having an npm script that cleans the generated files out before running `npx typewriter`

**Comment by oscb** [comment]
Hey @cjhensen 

To get typewriter to update the files you can run it like `npx typewriter -u` or `--update`. That will update the `plan.json` first then run the build.

By default it reads the `plan.json` if any to prevent pulling changes if you didn't intentionally expected them. I'll change the output to make it this clearer and revise our docs too!

Thanks!
