### ISSUE TITLE
Update minimum yaml version to 2.2.2

### ISSUE THREAD

**Issue by cajotafer** [segmentio/typewriter#305]
Hi, we're trying to mitigate all the vulnerabilities in our code base and typewriter has a few, one of them, easy to fix, is regarding yaml. There is a vulnerability with the current version that can be patched updating to the version 2.2.2 at least.

More info here https://github.com/advisories/GHSA-f9xv-q969-pqx4

**Comment by oscb** [comment]
Hi @cajotafer 
Upgraded `yaml` to the latest in the latest release: https://github.com/segmentio/typewriter/releases/tag/v9.1.0 
Thanks for reporting!
