### ISSUE TITLE
Support for Named Exports

### ISSUE THREAD

**Issue by fforres** [segmentio/typewriter#41]
I came across this while implementing Typewriter on an internal project. After doing some manual refactoring a few times I think it'd be great to have this baked in into Typewriter.

Currently typewriter exports wraps all your tracking calls inside a class you can instance to execute and allows you to pass an analytics instance.
i.e.

## Current Status
<details><summary>Show</summary>
<p>

```
const genOptions = (context = {}) => ({
  context: {
    ...context,
    typewriter: {
      name: "gen-js",
      version: "5.1.1"
    }
  }
});
export default class Analytics {
  constructor(analytics) {
    this.analytics = analytics || { track: () => null };
  }
  someThingToTrack(props, context) {
    this.analytics.track("Tracking a Thing", props, genOptions(context));
  }
  (... Many other methods)
}
```

</p>
</details>

We where using only a few of those tracking methods in our specific project, so we where shipping a lot of unused code that we weren't able to treeshake.
While it might not look like a a huge code reduction if we add the `--runtimeValidation false` flag, but it is if we want to keep those 😢

So after talking with @colinking on slack, he mentioned making this issue could be a good first step into the discussion.

## Proposal

Final export (after running `typewriter gen-js` with some flags i.e `--runtimeValidation false --export class`) would look like this:

<details><summary>Show</summary>
<p>

```
let analytics = (window && window.analytics) || { track: () => null } 

export const setaAnalytics = (newAnalytics) => { analytics = newAnalytics }

const genOptions = (context = {}) => ({
  context: {
    ...context,
    typewriter: {
      name: 'gen-js',
      version: '5.0.1'
    }
  }
})


export const someThingToTrack = (props, context, callback = () => {}) => {
  analytics.track('Tracking a Thing', props, genOptions(context), callback)
}

```
</p>
</details>

## Explanation 
- Implements a new flag `--export` with parameters `class` & `named-exports` (or `functions`?) 
	- We set `class` as the default value for it to keep backwards compatibility
- Makes every method now a named export
- Enables a module variable to be the instance of analytics.js
	- Adds method to be able to override that variable
- Adds support for the [`callback` parameter](https://segment.com/docs/sources/website/analytics.js/#track)

## Final Thoughts
- Easier tree shake / dead code elimination 
- Yei for smaller bundle sizes ❤️

**Comment by fforres** [comment]
1)
> Are you all looking to keep the runtimeValidation code in, during production?
Not in our case, no. Now that I think about it, maybe is not something that people would do in their prod bundle.
On the same point, and I might be derailing the conversation. Have we considered doing something like what react does for code elimination? 
When bundling their library they look at the env variables and removes all the warnings/dev-only code if `NODE_ENV=production`.

2) I'd have to test that. I'll bring some data in a bit :p 
   Also, unsure on the size across different plans / users. Maybe our specific tracking plan is small enough that is not important?
   But since our tracking plan is not tied to only one project, It'd be great to allow for the bundling pipeline to make that call for you.

3) `b`

I think we can bring more data to make a proper decision, while for a some of our tracking plans it does feel small enough to be negligible, unsure of the big picture here 🤔

**Comment by fforres** [comment]
❤️ @colinking you rock!! :D

**Comment by colinking** [comment]
❤️ @fforres

HMU if Brex is interested in trying out Typewriter!

**Comment by fforres** [comment]
We are. 
I'm a big advocate for protocols / define our tracking-plan ( and `tw` specially 😄 )
It's taking me more than I hoped for to get someone that can help us with that 😅,
but we are getting there 🤘
