### ISSUE TITLE
Android Kotlin Support

### ISSUE THREAD

**Issue by UshneshaDaripa** [segmentio/typewriter#62]
# Thanks for taking the time to contribute to Typewriter!

It is highly appreciated that you take the time to help improve Typewriter.
We appreciate it if you would take the time to write up a bug report or feature request.

Sadly, if we don't receive enough information, or the issue/feature request doesn't
align well with our roadmap, we might respectfully thank you for your time, and close the issue.

_Bug fixes and documentation fixes are welcome._

## In the case of a bug report 🐞

Please consider the following items when filing a bug report:

* Issue and steps to reproduce.
* Versions. (Typewriter, OS, language, etc.)
* Screenshots.
* Expected.
* Actual.
* Minimal reproducible example.

## In the case of a feature proposal ✍️

Please detail the following items when filing a feature request:

* Any proposed changes, if relevant.
* The problem that this feature addresses.

## In the case of a language proposal 🗺

Please detail the following items when filing a language proposal:

* A proposed API (for the CLI and for analytics functions in the new client).
* Explain what library you would use for run-time JSON Schema validation.
* Whether the language will support build-time validation.
* Any language-specific considerations

See the [contributing guide](CONTRIBUTING.md) for more details.

## Respect earns Respect 👏

Please respect our [Code of Conduct](CODE_OF_CONDUCT.md), in short:

* Using welcoming and inclusive language.
* Being respectful of differing viewpoints and experiences.
* Gracefully accepting constructive criticism.
* Focusing on what is best for the community.
* Showing empathy towards other community members.

**Comment by UshneshaDaripa** [comment]
can Typewriter auto generated code be in Kotlin?

**Comment by colinking** [comment]
@UshneshaDaripa we don't support generating clients in Kotlin, however we do support generating clients in Java (for `analytics-android`) and you can use Kotlin/Java interop: https://kotlinlang.org/docs/reference/java-interop.html

**Comment by oscb** [comment]
Support for `analytics-kotlin` was finally added in [v8](https://github.com/segmentio/typewriter/releases/tag/v8.0.4) fixes this issue
