### ISSUE TITLE
Gif not working

### ISSUE THREAD

**Issue by bbeaird** [segmentio/typewriter#78]
The gif in the readme, which is helpful for explaining what Typewriter does is busted :-(

**Comment by colinking** [comment]
Darn, is this still busted for you? Seems to work for me (on Chrome) on GitHub and on npm:

- https://github.com/segmentio/typewriter
- https://www.npmjs.com/package/typewriter

If so, what browser are you using?

**Comment by colinking** [comment]
Closing for now, but feel free to re-open if this is still an issue :)
