### ISSUE TITLE
PostInstall Fails on Snyk 

### ISSUE THREAD

**Issue by smcguinness** [segmentio/typewriter#79]
When following the docs on [Segment Official Docs ](https://segment.com/docs/protocols/typewriter/#browser-quickstart), I get stuck at the very first command `npm install --save-dev typewriter@next`. The install fails as it is attempting to run a `snyk protect` command on post install. 

![Screen Shot 2019-10-17 at 5 33 56 PM](https://user-images.githubusercontent.com/61205/67053110-05263a80-f106-11e9-8167-38f0190822fe.png)

If I get passed the post install by using the `-- ignore-scripts` option I then again get the same issue when running `npx typewriter@next init`. 

I tried to look at the code for the installed version, but the installed version does not seem to have a release tag on the repo.

**Comment by colinking** [comment]
Hey @smcguinness! Thanks for reporting this. We recently removed `snyk` from the `postinstall` script in one of the more recent pre-releases.

If you re-run this, it should pull a more recent pre-release (7.0.0-47) with this issue fixed. Let me know when you get a chance to give it another shot :)

**Comment by colinking** [comment]
> I tried to look at the code for the installed version, but the installed version does not seem to have a release tag on the repo.

The code for the pre-release branch of typewriter is available here: https://github.com/segmentio/typewriter/pull/59

**Comment by smcguinness** [comment]
@colinking Thanks so much for getting back with me so quickly. That new version published fixed the issue. 👍
