### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by wfortin** [segmentio/typewriter#85]
Hi, I would like to propose typewriter support for `@segment/analytics-react-native`, it seems that with few small modification to the `analytics-node` templates, we could add support for it. Would you be open for a PR for this?

**Comment by colinking** [comment]
Hey @wfortin! That'd be great! 🎉 If you open a PR, feel free to tag me and I'll take a look.

If you add the changes to templates, it would be great to also add a test for it here: https://github.com/segmentio/typewriter/tree/master/tests/e2e

All it needs is a minimal React Native app, such that it can boot and fire [these events](https://github.com/segmentio/typewriter/blob/1cf634a46e75d7613a6034fc524a82ba2913cfb1/tests/e2e/suite.test.ts#L48-L338). [Here's an example from `analytics-node`](https://github.com/segmentio/typewriter/blob/1cf634a46e75d7613a6034fc524a82ba2913cfb1/tests/e2e/node-typescript/index.ts#L32).

**Comment by wfortin** [comment]
Oof, I didn't think of the e2e tests to cover that. Setting up a proper e2e test infrastructure for react-native can be a pain. I'll see if that is worth the hassle for me to take on 😉 . Thanks for the quick response.

**Comment by colinking** [comment]
Sounds good, feel free to ping me if you have any questions!

**Comment by jonhilmarg** [comment]
hi @colinking , has there been any further discussion on adding support for `[@segment/analytics-react-native](https://github.com/segmentio/analytics-react-native)` ? We have a project that would greatly appreciate it.

**Comment by mpj** [comment]
It would be really nice to at least get some response from Segment on this. Since our core product is react native, this would have high value for us, so if, like the OP suggests, would only require small changes on top of analytics-node, I'd like to apply a little pressure to get it done. 😘

**Comment by oscb** [comment]
[v8](https://github.com/segmentio/typewriter/releases/tag/v8.0.4) has support for RN now. It shows up during `typewriter init` or you can set the SDK to `analytics-react-native` in your config file
